Improved interactive setup script
- Allow case insensitive input for questions
- Fetch repos in the right directory
- Allow user to directly start docker containers
- Allow user to directly open the site in broser

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -14,6 +14,10 @@ GITREPO_METHOD=""
 SETTING_AUTORUN=false
 
 
+# Navigate to repository root so we clone stuff in the right place
+cd "$(dirname "$0")/../"
+
+
 # Most importantly, center and output our logo ascii art
 TERM_SIZE=`tput cols`
 LOGO_SIZE=25
@@ -71,11 +75,11 @@ fi
 while [ "" == "$GITHUB_USER" ]; do
   GITHUB_USER=`git config --get github.user`
   if [ "$GITHUB_USER" != "" ]; then
-    INPUT_DEFAULT="[$GITHUB_USER]"
+    INPUT_DEFAULT=" [$GITHUB_USER]"
   else
     INPUT_DEFAULT=""
   fi
-  read -p "What is your GitHub username $INPUT_DEFAULT? " GITHUB_USER
+  read -p "What is your GitHub username$INPUT_DEFAULT? " GITHUB_USER
 
   if [[ "$GITHUB_USER" == "" ]]; then
     echo "Please provide your GitHub username in order for us to find your forks."
@@ -85,8 +89,8 @@ done
 
 # Prompt the user to select which server repo he wants to use
 while [ "" == "$GITREPO_SERVER" ]; do
-  INPUT_DEFAULT="[$GITHUB_USER/hummingbird-server]"
-  read -p "What's the name of your hummingbird-server repository fork $INPUT_DEFAULT? " GITREPO_SERVER
+  INPUT_DEFAULT=" [$GITHUB_USER/hummingbird-server]"
+  read -p "What's the name of your hummingbird-server repository fork$INPUT_DEFAULT? " GITREPO_SERVER
 
   if [[ "$GITREPO_SERVER" == "" ]]; then
     GITREPO_SERVER="$GITHUB_USER/hummingbird-server"
@@ -96,8 +100,8 @@ done
 
 # Prompt the user to select which client repo he wants to use
 while [ "" == "$GITREPO_CLIENT" ]; do
-  INPUT_DEFAULT="[$GITHUB_USER/hummingbird-client]"
-  read -p "What's the name of your hummingbird-client repository fork $INPUT_DEFAULT? " GITREPO_CLIENT
+  INPUT_DEFAULT=" [$GITHUB_USER/hummingbird-client]"
+  read -p "What's the name of your hummingbird-client repository fork$INPUT_DEFAULT? " GITREPO_CLIENT
 
   if [[ "$GITREPO_CLIENT" == "" ]]; then
     GITREPO_CLIENT="$GITHUB_USER/hummingbird-client"
@@ -107,8 +111,8 @@ done
 
 # Prompt the user to select which way he want to clone the repositories
 while [ "" == "$GITREPO_METHOD" ]; do
-  INPUT_DEFAULT="[HTTPS/ssh]"
-  read -p "Which method do you want to use for cloning your repositories $INPUT_DEFAULT? " GITREPO_METHOD
+  INPUT_DEFAULT=" [HTTPS/ssh]"
+  read -p "Which method do you want to use for cloning your repositories$INPUT_DEFAULT? " GITREPO_METHOD
 
   if [[ "$GITREPO_METHOD" == "" ]]; then
     GITREPO_METHOD="https"
@@ -117,18 +121,22 @@ done
 
 
 # Prompt the user to ask if he wants to start all containers after cloning
-INPUT_DEFAULT="[Y/n]"
-read -p "Do you want to start all containers after the initial setup $INPUT_DEFAULT? " 
+INPUT_DEFAULT=" [Y/n]"
+read -p "Do you want to start all containers after the initial setup$INPUT_DEFAULT? " SETTING_AUTORUN
+
+if [[ "$SETTING_AUTORUN" == "" ]]; then
+  SETTING_AUTORUN="y";
+fi
 
 if [[ "$SETTING_AUTORUN" == *"y"* || "$SETTING_AUTORUN" == *"Y"* ]]; then
-  SETTING_AUTORUN=true
+  SETTING_AUTORUN=1
 else
-  SETTING_AUTORUN=false
+  SETTING_AUTORUN=0
 fi
 
 
-# Fetch contributors project repositories from GitHub
-if [[ "$GITREPO_METHOD" == "ssh" ]]; then
+# Map the users input to a valid GitHub repository
+if [[ "$GITREPO_METHOD" == *"ssh"* || "$GITREPO_METHOD" == *"SSH"* ]]; then
   REPO_SERVER="git@github.com:$GITREPO_SERVER.git"
   REPO_CLIENT="git@github.com:$GITREPO_CLIENT.git"
 else
@@ -136,11 +144,87 @@ else
   REPO_CLIENT="https://github.com/$GITREPO_CLIENT.git"
 fi
 
-git clone "$REPO_SERVER" ./hummingbird-server
-git clone "$REPO_CLIENT" ./hummingbird-client
+
+# Check if all the user's input is correct
+if [[ $SETTING_AUTORUN -eq 0 ]]; then
+  DOES_AUTORUN=" NOT"
+else
+  DOES_AUTORUN=""
+fi
+
+echo -e "\n"
+echo "Thanks for providing all of your information."
+echo "We will use $GITREPO_METHOD to access GitHub in order to"
+echo "Clone hummingbird-server from $REPO_SERVER"
+echo "Clone hummingbird-client from $REPO_CLIENT"
+echo "And then$DOES_AUTORUN start everything automatically."
+echo -e "\n"
+
+INPUT_DEFAULT=" [Y/n]"
+read -p "Is that ok for you$INPUT_DEFAULT? " SETTING_CONFIRM
+echo -e "\n"
+
+if [[ "$SETTING_CONFIRM" == "" ]]; then
+  SETTING_CONFIRM="y";
+fi
+
+if [[ "$SETTING_CONFIRM" != *"y"* && "$SETTING_CONFIRM" != *"Y"* ]]; then
+  exit 0
+fi
 
 
-# Spin up
+# Fetch contributors project repositories from GitHub
+echo -e "\nAttempting to clone $REPO_SERVER to ./server"
+git clone "$REPO_SERVER" ./server
+
+echo -e "\nAttempting to clone $REPO_CLIENT to ./client"
+git clone "$REPO_CLIENT" ./client
+
+
+# Attempting to run everything, check if sub-repos have been cloned
+if [[ ! -d ./server ]]; then
+  echo "Sorry, we cannot automatically start everything. /server is missing!"
+  exit 1
+fi
+
+if [[ ! -d ./client ]]; then
+  echo "Sorry, we cannot automatically start everything. /client is missing!"
+  exit 1
+fi
+
+
+# Make the user very happy
+echo -e "\n"
+echo "Awesome, everything is ready to be built!"
+echo -e "\n"
+
+
+# If we got to this point, everything should be fine to be built
 docker-compose build
 docker-compose run --rm server rake db:setup
 docker-compose run --rm server rake db:setup RAILS_ENV=test
+
+
+# Automatically run bin/start if that option was accepted
+if  [[ $SETTING_AUTORUN -eq 1 ]]; then
+  bash ./bin/start
+
+
+  # Prompt if the link should be opened
+  INPUT_DEFAULT=" [Y/n]"
+  echo -e "\nInstallation completed successfully."
+  read -p "Do you want to open the site in your browser now$INPUT_DEFAULT? " OPEN_CONFIRM
+
+  if [[ "$OPEN_CONFIRM" == "" ]]; then
+    OPEN_CONFIRM="y";
+  fi
+
+  if [[ "$OPEN_CONFIRM" == *"y"* || "$OPEN_CONFIRM" == *"Y"* ]]; then
+    bash ./bin/open
+  else
+    echo -e "\nYou can open the site in your browser manually or run bin/open"
+  fi
+else
+  echo -e "\nInstallation complete. You may start everything by running bin/start"
+  echo "Afterwards, you can open the site in your browser by running bin/open"
+fi
